name: Deploy to Render (and report to GitHub)

on:
  push:
    branches:
      - master

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment (in_progress)
        id: create_deploy
        uses: actions/github-script@v7
        with:
          script: |
            const res = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              required_contexts: [],   // allow running without status checks
              auto_merge: false
            });
            core.setOutput('deployment_id', res.data.id);

      - name: Trigger Render Deploy Hook
        id: trigger
        env:
          HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          set -e
          # Fire the hook and fail if non-2xx
          curl -fsS -X POST "$HOOK"

      - name: Mark Deployment success (fire-and-forget)
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.create_deploy.outputs.deployment_id }},
              state: 'success',              // shows the green "Deployment" badge
              environment: 'production',
              log_url: 'https://dashboard.render.com/', // optional
              description: 'Triggered Render deployment via deploy hook.'
            });

      - name: Mark Deployment failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.create_deploy.outputs.deployment_id }},
              state: 'failure',
              environment: 'production',
              description: 'Failed to trigger Render deploy hook.'
            });
